branches:
  only:
    - master
#    - develop

language: perl6

perl6:
  - latest

before_install:
  - sh $TRAVIS_BUILD_DIR/Travis-ci/install-mongodb.sh 2.6.11
  - sh $TRAVIS_BUILD_DIR/Travis-ci/install-mongodb.sh 3.2.9

install:
  - rakudobrew build zef
#  - zef --debug --/test install Crane
#  - zef --debug --/test install Config::TOML
  - zef --/test --depsonly install .

# Cannot use the mongod service because the version is too low (2.4.12)
#services:
#  - mongodb

#git:
#  depth: 5

script:
#    - PERL6LIB=src prove -v -r --exec=perl6 tests/
    - PERL6LIB=lib prove -v --exec=perl6 xt/001-meta.t
    - PERL6LIB=lib prove -v --exec=perl6 t/
    - PERL6LIB=lib prove -v --exec=perl6 xt/Basic || echo 'ignore failures'


#cache:
#  timeout: 1200
#  directories:
#    - $HOME/Travis-ci
#    - $HOME/.rakudobrew
