branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-zef ${TRAVIS_PERL6_VERSION#latest}
  - zef --depsonly install .
  - sh $TRAVIS_BUILD_DIR/Travis-ci/install-mongodb.sh 3.2.9

# Cannot use the mongod service because the version is too low (2.4.12)
#services:
#  - mongodb

git:
  depth: 5

cache:
#  timeout: 1200
  directories:
    - $HOME/Travis-ci
    - $HOME/.rakudobrew
