branches:
  only:
    - master

language: perl6

perl6:
  - latest
#  - '2017.05'

before_install:
  - sh $TRAVIS_BUILD_DIR/Travis-ci/install-mongodb.sh 3.2.9

install:
  - rakudobrew build zef
#  - zef --debug --/test install Crane
#  - zef --debug --/test install Config::TOML
  - zef --/test --depsonly install .

# Cannot use the mongod service because the version is too low (2.4.12)
#services:
#  - mongodb

git:
  depth: 5

#cache:
#  timeout: 1200
#  directories:
#    - $HOME/Travis-ci
#    - $HOME/.rakudobrew
