#dist: precise
dist: trusty   # default after august 2017

branches:
  only:
    - master
#    - develop
#    - accounting

language: perl6

perl6:
  - latest

before_install:
  # See also https://www.mongodb.org/dl/linux/
  - sh $TRAVIS_BUILD_DIR/t/Travis-ci/install-mongodb.sh 2.6.11
  - sh $TRAVIS_BUILD_DIR/t/Travis-ci/install-mongodb.sh 3.2.9

install:
  - rakudobrew build zef
#  - zef --debug --/test install Crane
#  - zef --debug --/test install Config::TOML
  - zef --/test --depsonly install .

# Cannot use the mongod service because the version is too low (2.4.12)
#services:
#  - mongodb

#git:
#  depth: 5

script:
  - xt/wrapper.pl6 xt/001-meta.t
  - xt/wrapper.pl6 t/098-mk-sandbox.t

  - xt/wrapper.pl6 --serverkeys=s1 t/099* t/[2-5]* t/998*
  - xt/wrapper.pl6 --serverkeys=s4 t/099* t/[2-5]* t/998*
  - xt/wrapper.pl6 --ignore xt/Basic

  - xt/wrapper.pl6 --serverkeys=s1,s2 --ignore t/099* xt/Behavior/1* t/998*
  - xt/wrapper.pl6 --serverkeys=s4,s5 --ignore t/099* xt/Behavior/1* t/998*

  - xt/wrapper.pl6 --serverkeys=s1,s2,s3 --ignore t/099* xt/Behavior/6* t/998*
  - xt/wrapper.pl6 --serverkeys=s4,s5,s6 --ignore t/099* xt/Behavior/6* t/998*

  - xt/wrapper.pl6 t/999-rm-sandbox.t


#cache:
#  timeout: 1200
#  directories:
#    - $HOME/Travis-ci
#    - $HOME/.rakudobrew
