os: Visual Studio 2015

platform: x64

branches:
  # whitelist
  only:
    - master
#    - windows
#    - develop
#    - dummy-branch

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

  - ps: |
      choco feature enable -n allowGlobalConfirmation
      choco feature enable -n allowEmptyChecksums

      $workdir = "C:\projects\mongo-perl6-driver"
      $insdir = "t\Appveyor\install"
      $mdbname = "mongodb-win32-x86_64-2008plus-ssl-3.6.4"

      # install mongodb
      Invoke-WebRequest -Uri "https://downloads.mongodb.org/win32/$mdbname.zip" -OutFile "$workdir\$insdir\mongodb.zip"
      Expand-Archive "$workdir\$insdir\mongodb.zip" "$workdir\$insdir"
      mklink /J "$workdir\$insdir\bin" "C:\$workdir\$insdir\$mdbname\bin"

      choco install strawberryperl

      Invoke-WebRequest -Uri "https://rakudo.org/latest/star/win64" -OutFile "C:\$workdir\$insdir\rakudo.msi"
      msiexec /i "C:\$workdir\$insdir\rakudo.msi" /quiet /qn /norestart /log "C:\workdir\$insdir\rakudo-install.log"

      $path = "C:\$workdir\$insdir\$mdbname\bin;" +
        "C:\strawberry\c\bin;" +
        "C:\strawberry\perl\site\bin;" +
        "C:\strawberry\perl\bin;" +
        "C:\rakudo\bin;" +
        "C:\rakudo\share\perl6\site\bin"

      [Environment]::SetEnvironmentVariable( "PATH", "$path%PATH%", "User")

#  - zef --/test install Log::Async
#  - zef --/test install Config::TOML
#  - zef --/test install Auth::SCRAM
#  - zef --/test install Base64
#  - zef --/test install OpenSSL
#  - zef --/test install Unicode::PRECIS
#  - zef --/test install Config::DataLang::Refine

  - zef --/test --depsonly install .

build: off

test_script:
  - perl6 xt/wrapper.pl6 t/098-mk-sandbox.t
  - perl6 xt/wrapper.pl6 --serverkeys=s7 t/099* t/[2-5]* t/998*
  - perl6 xt/wrapper.pl6 t/999-rm-sandbox.t

# fetch repository as zip archive
#shallow_clone: true

# set clone depth
clone_depth: 5

environment:
  Test-Env: AppVeyor
