os: Visual Studio 2015

platform: x64

branches:
  # whitelist
  only:
#    - master
#    - windows
#    - develop
    - dummy-branch

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

  - ps: |
      choco feature enable -n allowGlobalConfirmation
      choco feature enable -n allowEmptyChecksums

      $workdir = "C:\projects\mongo-perl6-driver"
      $insdir = "t\Appveyor"
      $mdbname = "mongodb-win32-x86_64-2008plus-ssl-3.6.4"

      # install mongodb
      Invoke-WebRequest -Uri "https://downloads.mongodb.org/win32/$mdbname.zip" -OutFile "$workdir\$insdir\mongodb.zip"
      Expand-Archive "$workdir\$insdir\mongodb.zip" "$workdir\$insdir"

      choco install strawberryperl

      # Invoke-WebRequest -Uri "https://rakudo.org/latest/star/win64" -OutFile "$workdir\$insdir\rakudo.msi"
      Invoke-WebRequest -Uri "https://rakudo.org/dl/star/rakudo-star-2018.01-x86_64 (JIT).msi" -OutFile "$workdir\$insdir\rakudo.msi"
      # appveyor DownloadFile   "https://rakudo.org/dl/star/rakudo-star-2018.01-x86_64 (JIT).msi" -FileName $workdir\$insdir\rakudo.msi
      msiexec /i "$workdir\$insdir\rakudo.msi" /quiet /qn /norestart /log "workdir\$insdir\rakudo-install.log"

      <#
        $path = "$workdir\$insdir\$mdbname\bin;" +
          "C:\strawberry\c\bin;" +
          "C:\strawberry\perl\site\bin;" +
          "C:\strawberry\perl\bin;" +
          "C:\rakudo\bin;" +
          "C:\rakudo\share\perl6\site\bin;" +
          "%PATH%"
        [Environment]::SetEnvironmentVariable( "PATH", $path, "User")
      #>

  - SET PATH=C:\projects\mongo-perl6-driver\t\Appveyor\mongodb-win32-x86_64-2008plus-ssl-3.6.4\bin;%PATH%
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%

  # some features to enable
#  - choco feature enable -n allowEmptyChecksums
#  - choco feature enable -n allowGlobalConfirmation

  # https://www.mongodb.org/dl/win32/x86_64-2008plus-ssl
#  - appveyor DownloadFile "http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.4.zip" -FileName C:\projects\mongo-perl6-driver\mongodb.zip
#  - ps: Expand-Archive C:\projects\mongo-perl6-driver\mongodb.zip .
#  - mklink /J .\mongodb-3.6.4 \mongodb-win32-x86_64-2008plus-ssl-3.6.4\bin
#  - echo %APPVEYOR_BUILD_FOLDER%
#  - dir %APPVEYOR_BUILD_FOLDER%

  # This will be the latest version
#  - choco install mongodb

#  - choco install strawberryperl
#  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

    # See also https://rakudo.org/files
    # Powershell 2
#    $webClient = New-Object System.Net.WebClient
#    $webClient.DownLoadFile( "https://rakudo.org/latest/star/win64", "C:\projects\mongo-perl6-driver\rakudo.msi")
    # Powershell 3
#  - Invoke-WebRequest -Uri "https://rakudo.org/latest/star/win64" -OutFile "C:\projects\mongo-perl6-driver\rakudo.msi"
#  - appveyor DownloadFile "https://rakudo.org/latest/star/win64" -FileName C:\projects\mongo-perl6-driver\rakudo.msi"
#  - appveyor DownloadFile   "https://rakudo.org/dl/star/rakudo-star-2018.01-x86_64 (JIT).msi" -FileName C:\projects\mongo-perl6-driver\rakudo.msi
#  - msiexec /i C:\projects\mongo-perl6-driver\rakudo.msi /quiet /qn /norestart /log install.log

#  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
#  - zef --/test install Log::Async
#  - zef --/test install Config::TOML
#  - zef --/test install Auth::SCRAM
#  - zef --/test install Base64
#  - zef --/test install OpenSSL
#  - zef --/test install Unicode::PRECIS
#  - zef --/test install Config::DataLang::Refine

  - zef --/test --depsonly install .

build: off

test_script:
  - perl6 xt/wrapper.pl6 t/098-mk-sandbox.t
  - perl6 xt/wrapper.pl6 --serverkeys=s7 t/099* t/[2-5]* t/998*
  - perl6 xt/wrapper.pl6 t/999-rm-sandbox.t

# fetch repository as zip archive
#shallow_clone: true

# set clone depth
clone_depth: 5

environment:
  Test-Env: AppVeyor
