[Binaries]
  mongod = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Travis-ci/MongoDB/mongod'

[mongod]
  nojournal = true
  fork = true
  smallfiles = true
  oplogSize = 128
  #ipv6 = true
  #quiet = true
  #verbose = '=command=v =nework=v'
  verbose = 'vv'
  logappend = true


# Configuration for Server 1
#
[mongod.s1]
  logpath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server1/m.log'
  pidfilepath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server1/m.pid'
  dbpath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server1/m.data'
  port = 65010

[mongod.s1.replicate1]
  replSet = 'first_replicate'

# Configuration for Server 2
#
[mongod.s2]
  logpath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server2/m.log'
  pidfilepath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server2/m.pid'
  dbpath = '/home/marcel/Languages/Perl6/Projects/mongo-perl6-driver/Sandbox/Server2/m.data'
  port = 65011

[mongod.s2.replicate1]
  replSet = 'first_replicate'

[mongod.s2.replicate2]
  replSet = 'second_replicate'

[mongod.s2.authenticate]
  auth = true

